name: ghcr-push

on:
  push:
    tags:
      - '*'

jobs:
  ghcr-push:
    runs-on: ubuntu-latest
    environment: ghcr-push
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: docker build and push
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          docker build -t ghcr.io/${{ github.repository }}:$IMAGE_TAG .
          docker push ghcr.io/${{ github.repository }}:$IMAGE_TAG
