name: ghcr-push

on:
  push:
    tags:
      - '*'

jobs:
  ghcr-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build and push
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          GO_VERSION=$(grep '^go' go.mod | cut -d ' ' -f2)
          docker build \
            --build-arg GO_VERSION=$GO_VERSION \
            --tag ghcr.io/${{ github.repository }}:$IMAGE_TAG \
            .
          docker push ghcr.io/${{ github.repository }}:$IMAGE_TAG
